"""Frozen internal constants for Phase 2 route-candidate generation."""


ROUTE_COMPARISON_SAMPLE_INTERVAL_M = 50.0
ROUTE_SPATIAL_MATCH_TOLERANCE_M = 35.0
ROUTE_SIMILARITY_DIRECTIONAL_THRESHOLD = 0.85

MAXIMUM_ROUTE_DURATION_MULTIPLIER = 1.5
RELAXED_ROUTE_DURATION_MULTIPLIER = 1.8
RELAXED_ROUTE_ADDITIONAL_SECONDS = 600.0
MINIMUM_MEANINGFUL_ROUTES = 2
TARGET_MEANINGFUL_ROUTES = 3
MAXIMUM_MEANINGFUL_ROUTES = 3

MINIMUM_WAYPOINT_ENDPOINT_DISTANCE_M = 150.0
MINIMUM_JOURNEY_FOR_WAYPOINT_M = 300.0
WAYPOINT_SEARCH_CORRIDOR_RADIUS_M = 600.0
MINIMUM_WAYPOINT_ROUTE_OFFSET_M = 35.0
MINIMUM_WAYPOINT_ROUTE_PROGRESS = 0.10
MAXIMUM_WAYPOINT_ROUTE_PROGRESS = 0.90
MAXIMUM_WAYPOINT_GEOMETRIC_DETOUR_MULTIPLIER = 1.5
MAXIMUM_WAYPOINT_ATTEMPTS = 2
MAXIMUM_MAPBOX_REQUESTS = 3
